replicaCount: 1

image:
  repository: httpd
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetport: 30020

persistentVolume:
  enabled: true
  hostPath: /home/clinton/kafka/data
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  reclaimPolicy: Retain

website:
  mountPath: /usr/local/apache2/htdocs/
#   mountPath: /
