apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-apache-pvc
spec:
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: ""
  volumeName: {{ .Release.Name }}-apache-pv
