apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-apache-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  hostPath:
    path: "/mnt/localfolder"
