apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30080
  selector:
    app: {{ .Chart.Name }}



